databaseChangeLog:
  - changeSet:
      id: 1
      author: ja
      changes:
        - createTable:
            tableName: DOCTORS
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: email
                  type: varchar(255)
                  constraints:
                    unique: true
              - column:
                  name: first_name
                  type: varchar(255)
              - column:
                  name: last_name
                  type: varchar(255)
              - column:
                  name: password
                  type: varchar(255)



